### ISSUE TITLE
Doesn't save code

### ISSUE THREAD

**Issue by Scoffins** [prathamVaidya/supercode-tinymce-plugin#8]
If you make changes in the codeview then try to submit the form without first switching back to editor view, the changes arent saved and are lost. This is incredibly frustrating for me, so I imagine it would be infuriating for users.

**Comment by prathamVaidya** [comment]
Thanks for pointing it out, I'll push a fix for this ASAP.

**Comment by prathamVaidya** [comment]
@Scoffins here is the PR that adds a live save for the in-view editor mode and fixes your issue.

LMK if you can review or test this yourself https://github.com/prathamVaidya/supercode-tinymce-plugin/pull/9.

I have tested and self-reviewed it. I'll close this in a day after some more tests.
